### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by xowe1** [sambayless/golems#1]
I had tons of fun with Golems back in the day. Such a shame it appears to be dead. Is an update planned in the future?d

**Comment by michalusio** [comment]
I remember Golems too - been making engines and stuff.
It's sad that the project's dead, as it's the only good-enough physics sandbox for 3D I found that's not commercial.

I am a bit rusty on Java, but if someone else also wanted to volunteer, I would be happy to help with forking the project and doing maintenance.

**Comment by sambayless** [comment]
I'm glad you both have fond memories of Golems!

I had a lot of fun making it, but I don't expect to be able to continue developing it, sadly.
If anyone wants to fork it and put some time into resurrecting it, I'd be happy to endorse a fork
